### ISSUE TITLE
Patcher request

### ISSUE THREAD

**Issue by pakodx** [ShadowOne333/MaternalBound-Redux#1]
hello! 
I would like to request a custom patcher for materbound redux, similar to Secret of mana turbo
https://www.romhacking.net/forum/index.php?topic=27890.0
where you can choose which features you'd like implemented/patched in and which you don't.

I would love to play this, but there are some changes I don't agree with and I would like to be able to leave them out.

thank you!

**Comment by ShadowOne333** [comment]
The whole reason of having the project here in GitHub and available for the public, is so that anyone can download it, make the changes they want and compile it back once the changes are done with CoilSnake.

Having a patcher of sorts wouldn't be of much help, since there will always be something that some user won't like.
It's better if the user itself downloads the project, makes the changes they want and compile it to get the result they want.

It's open source for that very reason.
