### ISSUE TITLE
Game glitches when entering a door

### ISSUE THREAD

**Issue by ExGuestCJ** [ShadowOne333/MaternalBound-Redux#6]

**Comment by ryanwholey** [comment]
I had an issue like this where there seemed to be a chance that whenever I would use a door the game could freeze (steam deck, patch 1.1). This was resolved by ultimately using the right base ROM. I switched from the ips patch to bps and patched on romhacking.net/patch/index.php, which then notified me that my base ROM checksum was wrong. I had to really search for a base with a CRC of AF607132, but once found, I haven't had the issue since.

**Comment by ExGuestCJ** [comment]
well i used the earthbound patcher and it worked

**Comment by ShadowOne333** [comment]
Thanks for confirming this @ryanwholey .
I've had many reports about this happening with MB Redux, and it's good to have confirmation that it's due to a wrong base ROM being used.

**Comment by ExGuestCJ** [comment]
> Thanks for confirming this @ryanwholey . I've had many reports about this happening with MB Redux, and it's good to have confirmation that it's due to a wrong base ROM being used.

tough i used the no intro rom

**Comment by ExGuestCJ** [comment]
also you need to improve your spanish translation, i have seen many nitpicks about it
